import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, Eye, FileDown, Loader2, Stamp } from "lucide-react";
import { Badge, Button, Field, inputClass, Label } from "@/components/kit";
import { LETTER_TEMPLATES, getTemplate, nextReference, type LetterType } from "@/hr/letters";
import { openPdf, pdfBlobUrl, renderLetter } from "@/hr/pdf";
import type { Employee } from "./types";
import type { IssuedDocument } from "./repository";

/**
 * Draft → Issue.
 *
 * A DRAFT renders on the letterhead with the signature and stamp COVERED and a
 * watermark across it, so an unsigned letter can never be mistaken for a signed
 * one. Only "Issue" applies the real signature, mints a permanent reference,
 * embeds the verification QR, and writes it to the register.
 *
 * That distinction is the entire safety model of this module: the company's real
 * signature is on that letterhead, and issuing is therefore an act with weight.
 */
const LetterComposer = ({
  employees,
  documents,
  onIssue,
}: {
  employees: Employee[];
  documents: IssuedDocument[];
  /** Returns the SAVED document — the database mints its verify token. */
  onIssue: (doc: Omit<IssuedDocument, "id" | "createdAt">) => Promise<IssuedDocument>;
}) => {
  const [employeeId, setEmployeeId] = useState("");
  const [letterType, setLetterType] = useState<LetterType>("experience");
  const [values, setValues] = useState<Record<string, string>>({});
  const [preview, setPreview] = useState<string | null>(null);
  const [busy, setBusy] = useState<"preview" | "issue" | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [confirmIssue, setConfirmIssue] = useState(false);

  const employee = employees.find((e) => e.id === employeeId);
  const template = getTemplate(letterType);

  // Revoke the old blob when the preview changes — otherwise every render leaks
  // a PDF into memory.
  useEffect(() => () => {
    if (preview) URL.revokeObjectURL(preview);
  }, [preview]);

  const reference = useMemo(
    () => nextReference(documents.map((d) => d.reference)),
    [documents],
  );

  const missingRequired = template.fields
    .filter((f) => f.required && !values[f.key]?.trim())
    .map((f) => f.label);

  const canRender = Boolean(employee) && missingRequired.length === 0;

  const render = async (mode: "draft" | "issued", saved?: IssuedDocument) => {
    if (!employee) return null;

    return renderLetter({
      employee,
      letterType,
      values,
      mode,
      reference: saved?.reference,
      verifyToken: saved?.verifyToken,
      issuedAt: saved?.issuedAt ? new Date(saved.issuedAt) : new Date(),
      origin: window.location.origin,
    });
  };

  const handlePreview = async () => {
    setError(null);
    setBusy("preview");
    try {
      const bytes = await render("draft");
      if (bytes) {
        if (preview) URL.revokeObjectURL(preview);
        setPreview(pdfBlobUrl(bytes));
      }
    } catch (caught) {
      setError(caught instanceof Error ? caught.message : "Could not render the letter.");
    } finally {
      setBusy(null);
    }
  };

  const handleIssue = async () => {
    if (!employee) return;

    setError(null);
    setBusy("issue");
    try {
      /* Save BEFORE rendering. The verification token is generated by the
         database, so a PDF rendered first would carry a QR pointing at a token
         that does not exist. Register first, then print. */
      const saved = await onIssue({
        reference,
        verifyToken: "",
        letterType,
        employeeId: employee.id,
        employeeName: employee.fullName,
        status: "issued",
        subject: template.subject,
        body: template.build(employee, values),
        fields: values,
        issuedAt: new Date().toISOString(),
        issuedBy: "admin",
        revokedAt: null,
        revokeReason: null,
      });

      const bytes = await render("issued", saved);
      if (!bytes) return;

      openPdf(
        bytes,
        `${saved.reference.replace(/\//g, "-")}-${employee.fullName.replace(
          /\s+/g,
          "-",
        )}.pdf`,
      );

      setConfirmIssue(false);
      setValues({});
      if (preview) {
        URL.revokeObjectURL(preview);
        setPreview(null);
      }
    } catch (caught) {
      setError(caught instanceof Error ? caught.message : "Could not issue the letter.");
    } finally {
      setBusy(null);
    }
  };

  return (
    <div className="grid gap-8 lg:grid-cols-[1fr_1.1fr]">
      <div className="flex flex-col gap-7">
        <Field id="letter-employee" label="Employee">
          <select
            id="letter-employee"
            value={employeeId}
            onChange={(e) => setEmployeeId(e.target.value)}
            className={inputClass()}
          >
            <option value="">Select an employee…</option>
            {employees.map((e) => (
              <option key={e.id} value={e.id}>
                {e.fullName} — {e.role || "no role set"}
              </option>
            ))}
          </select>
        </Field>

        <Field id="letter-type" label="Letter">
          <select
            id="letter-type"
            value={letterType}
            onChange={(e) => {
              setLetterType(e.target.value as LetterType);
              setValues({});
            }}
            className={inputClass()}
          >
            <optgroup label="Employment">
              {LETTER_TEMPLATES.filter((t) => t.category === "employment").map((t) => (
                <option key={t.type} value={t.type}>
                  {t.title}
                </option>
              ))}
            </optgroup>
            <optgroup label="Exit & disciplinary">
              {LETTER_TEMPLATES.filter((t) => t.category === "exit").map((t) => (
                <option key={t.type} value={t.type}>
                  {t.title}
                </option>
              ))}
            </optgroup>
          </select>
        </Field>

        <p className="-mt-3 text-xs text-muted-foreground">{template.description}</p>

        {template.sensitive && (
          <div className="flex gap-3 rounded-2xl border border-amber-500/40 bg-amber-500/5 p-4">
            <AlertTriangle
              size={16}
              aria-hidden="true"
              className="mt-0.5 shrink-0 text-amber-500"
            />
            <p className="text-xs leading-relaxed text-muted-foreground">
              <span className="font-medium text-foreground">This letter has legal weight.</span>{" "}
              The stated reason is recorded permanently in the document register and cannot be
              edited afterwards. Write it as you would want it read back to you.
            </p>
          </div>
        )}

        {template.fields.map((field) => (
          <Field key={field.key} id={`f-${field.key}`} label={field.label}>
            {field.type === "textarea" ? (
              <textarea
                id={`f-${field.key}`}
                rows={4}
                value={values[field.key] ?? ""}
                onChange={(e) =>
                  setValues((v) => ({ ...v, [field.key]: e.target.value }))
                }
                placeholder={field.placeholder}
                className={inputClass("resize-none")}
              />
            ) : (
              <input
                id={`f-${field.key}`}
                type={field.type}
                value={values[field.key] ?? ""}
                onChange={(e) =>
                  setValues((v) => ({ ...v, [field.key]: e.target.value }))
                }
                placeholder={field.placeholder}
                className={inputClass()}
              />
            )}
          </Field>
        ))}

        {error && (
          <p role="alert" className="text-sm text-red-500">
            {error}
          </p>
        )}

        <div className="flex flex-wrap gap-3">
          <Button
            variant="secondary"
            onClick={handlePreview}
            disabled={!canRender || busy !== null}
          >
            {busy === "preview" ? (
              <Loader2 size={15} className="animate-spin" aria-hidden="true" />
            ) : (
              <Eye size={15} aria-hidden="true" />
            )}
            Preview draft
          </Button>

          <Button
            onClick={() => setConfirmIssue(true)}
            disabled={!canRender || busy !== null}
          >
            <Stamp size={15} aria-hidden="true" />
            Issue & sign
          </Button>
        </div>

        {!canRender && employee && (
          <p className="text-xs text-muted-foreground">
            Fill in: {missingRequired.join(", ")}.
          </p>
        )}

        {confirmIssue && employee && (
          <div className="surface p-6">
            <p className="text-sm font-medium text-foreground">
              Issue this letter with the company signature?
            </p>
            <p className="measure mt-2 text-sm leading-relaxed text-muted-foreground">
              This applies the real signature and stamp, assigns the permanent reference{" "}
              <span className="tabular-nums text-accent">{reference}</span>, and records it in
              the document register. It cannot be un-issued — only revoked.
            </p>

            <div className="mt-5 flex gap-3">
              <Button onClick={handleIssue} disabled={busy !== null}>
                {busy === "issue" ? (
                  <Loader2 size={15} className="animate-spin" aria-hidden="true" />
                ) : (
                  <FileDown size={15} aria-hidden="true" />
                )}
                Yes — issue {reference}
              </Button>
              <Button variant="ghost" onClick={() => setConfirmIssue(false)}>
                Cancel
              </Button>
            </div>
          </div>
        )}
      </div>

      <div className="flex flex-col">
        <div className="flex items-center justify-between">
          <Label>Preview</Label>
          <Badge tone="warning">Draft — unsigned</Badge>
        </div>

        <div className="surface mt-3 flex-1 overflow-hidden p-0">
          {preview ? (
            <iframe
              src={preview}
              title="Letter preview"
              className="h-full min-h-[38rem] w-full"
            />
          ) : (
            <div className="flex h-full min-h-[38rem] items-center justify-center p-8 text-center">
              <p className="measure text-sm text-muted-foreground">
                Choose an employee and a letter, then preview. The draft renders on the real
                letterhead with the signature and stamp covered — so an unsigned letter can
                never pass for a signed one.
              </p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default LetterComposer;
