export type EmployeeStatus = "active" | "inactive";
export type EmploymentType = "full-time" | "part-time" | "contract" | "intern";
export type WorkMode = "onsite" | "remote" | "hybrid";

export interface EmergencyContact {
  name: string;
  relationship: string;
  phone: string;
}

export interface Employee {
  id: string;
  /** Human-facing staff number: SL-2026-014. Assigned automatically. */
  employeeId: string;

  /**
   * Unguessable verification token, generated by the database.
   * The QR on an ID card carries THIS — never `employeeId`, which is sequential
   * and would let anyone enumerate the whole roster by counting upward.
   */
  verifyToken: string;

  fullName: string;
  role: string;
  department: string;
  manager: string;

  email: string;
  phone: string;
  cnic: string;
  dateOfBirth: string;
  address: string;

  status: EmployeeStatus;
  employmentType: EmploymentType;
  workMode: WorkMode;

  joinedAt: string;
  /** Probation length in months. Drives the confirmation-due automation. */
  probationMonths: number;
  exitDate: string;

  salaryAmount: number;
  salaryCurrency: string;

  emergencyContact: EmergencyContact;

  /** Storage path (Supabase) or a data URL (local adapter). */
  photoPath: string;
  notes: string;

  /** Publishing. Flipping this puts the person on the public website. */
  showOnWebsite: boolean;
  publicBio: string;
}

export type EmployeeDraft = Omit<Employee, "id">;

export const EMPTY_DRAFT: EmployeeDraft = {
  employeeId: "",
  verifyToken: "",
  fullName: "",
  role: "",
  department: "",
  manager: "",
  email: "",
  phone: "",
  cnic: "",
  dateOfBirth: "",
  address: "",
  status: "active",
  employmentType: "full-time",
  workMode: "onsite",
  joinedAt: "",
  probationMonths: 3,
  exitDate: "",
  salaryAmount: 0,
  salaryCurrency: "PKR",
  emergencyContact: { name: "", relationship: "", phone: "" },
  photoPath: "",
  notes: "",
  showOnWebsite: false,
  publicBio: "",
};

export const EMPLOYMENT_TYPES: EmploymentType[] = [
  "full-time",
  "part-time",
  "contract",
  "intern",
];
export const WORK_MODES: WorkMode[] = ["onsite", "remote", "hybrid"];
export const CURRENCIES = ["PKR", "USD", "EUR", "NOK", "GBP"];

/**
 * SL-2026-014 — company prefix, joining year, zero-padded sequence.
 *
 * The sequence is scoped to the YEAR, not the whole company, so numbers stay
 * short and a glance tells you when someone joined. Collisions are avoided by
 * taking max(existing sequence for that year) + 1 rather than counting rows —
 * counting breaks the moment anyone is deleted.
 */
export const nextEmployeeId = (existing: Employee[], joinedAt: string): string => {
  const year = joinedAt ? new Date(joinedAt).getFullYear() : new Date().getFullYear();
  const prefix = `SL-${year}-`;

  const highest = existing
    .map((e) => e.employeeId)
    .filter((id) => id.startsWith(prefix))
    .map((id) => Number.parseInt(id.slice(prefix.length), 10))
    .filter((n) => Number.isFinite(n))
    .reduce((max, n) => Math.max(max, n), 0);

  return `${prefix}${String(highest + 1).padStart(3, "0")}`;
};
